### ISSUE TITLE
Fail to Attach service

### ISSUE THREAD

**Issue by kaizhongchou** [DFRobot/DFRobot_SIM7000#8]
I use the DFRobot_SIM7000_UDP sample code, and I meet a big problem that fail to attach service.
I try a lot of function to connect the APN using AT+CSTT, AT+CIICR, AT+CIFSR those AT command, but i still can't  attach service.

**Comment by noyoladerose** [comment]
I got the same problem. The code failed to attach service. I tried with three mobile operator SIM cards.

**Comment by Boaz-Chang** [comment]
I got the same problem.
I use the DFRobot_SIM7000_MQTT sample code，
The code at attacthService() failed to attach service，
AT command AT+CIICR failed。

**Comment by metroIOT** [comment]
I have the same problem, the sim7000.attacthService(), fails on every example.   The AT command code works, and i can read HTTP data and FTP data, over Telstra NB-IOT, but the sim7000.attacthService() fails every time.  There must be a way to set the APN in these code example ???  cant find it

**Comment by sasasas1111** [comment]
有人解决了这个问题吗？

**Comment by sossnowski** [comment]
the same problem. Someone know how to solve it?

**Comment by wilba84** [comment]
Anybody work this out? have the module working perfectly with AT Tester, looks like we are all having the same issue

**Comment by chrisday-code** [comment]
Did anyone end up fixing this?

**Comment by wilba84** [comment]
Yeah there was a spelling error in the library

**Comment by wilba84** [comment]
I fixed it by going through the library and example code, and changing “attacth” to “attach” and it worked. Depending on what your doing, I would recommend using a different library

**Comment by danielkp1234** [comment]
I am having the same issue and i changed “attacth” to “attach” in the .h file and the .cpp but it still doesn't work

**Comment by danielkp1234** [comment]
@tangjie133 I also changed the apn in the .cpp file

**Comment by wilba84** [comment]
Dont use this library, its full of errors and in the end, I never got it to work correctly.
For the sim7000 your looking for the botletics library, in particular v 1.0.2.
When I used this it worked straight away and theres also alot of support on their github.
Hope this helps, if you get stuck let me know and ill send you some demo code ect

**Comment by danielkp1234** [comment]
@wilba84 I have looked at using the botletics library but I can't seem to get it working.

I tried this and a lot of other methods but i keep getting "Couldn't find Fona" and it doesnt respond to the AT command if i look in the serial monitor. 

I literally just want to send a simple HTTP POST or GET request containing the GPS latitude and longitude. I have been trying for days but nothing actually wants to work for me atm.

`#include "Adafruit_FONA.h"
#include <SoftwareSerial.h> 
#include <Wire.h>

#define ltePort 12

SoftwareSerial fonaSS = SoftwareSerial(8,7);
SoftwareSerial *fonaSerial = &fonaSS;
Adafruit_FONA_LTE fona = Adafruit_FONA_LTE();

void setup () {
Serial.begin(9600);
pinMode(ltePort,OUTPUT);
digitalWrite(ltePort,HIGH);
fonaSS.begin(9600);
delay(2000);
  if (! fona.begin(fonaSS)) {
    Serial.println(F("Couldn't find FONA"));
    while(1); // Don't proceed if it couldn't find the device
  }
}
void loop(){
  
}`


Do you have an example I could see that would be greatly appreciated

**Comment by wilba84** [comment]
I can send you some stuff when I get home from work.
Meanwhile, try the botletics library v1.0.2 and use hardware serial. The default baud for sim7000 is 115200, try changing yours from 9600

**Comment by danielkp1234** [comment]
@wilba84 Thanks,
I tried following this guide 
https://forum.core-electronics.com.au/t/dfrobot-sim7000-shield-guide/8280
and ended up trying this code a modified example from botletics with the right pins?
https://pastebin.com/ee0uSZ2n



But that doesn't seem to work my console outputs
![image](https://user-images.githubusercontent.com/19412591/163874657-7f178eb7-51f5-48da-a39d-181943704065.png)
![image](https://user-images.githubusercontent.com/19412591/163874685-3c7e5a9f-aa86-404b-b533-e10736e8f14e.png)

EDIT: Changing the library version down to 1.0.2 also didn't work with the code above

**Comment by wilba84** [comment]
try this, use the code from "SIM7XXX_LTE_Demo", make sure you switch the library over too. This works with my sim7000, and should give you an idea
[fona.zip](https://github.com/DFRobot/DFRobot_SIM7000/files/8508569/fona.zip)
Set your rx tx switch to D7/8 on the module.

**Comment by danielkp1234** [comment]
@wilba84 Okay that kinda works I tried using this code 
https://pastebin.com/pj1eaDzP

It finds the board (detects it as 7500 and not 7000 tho) but I can't get either GPRS or GPS to work.
This is the output of the serial monitor
![image](https://user-images.githubusercontent.com/19412591/164016930-44f15079-ed10-4ab4-8f9c-28fbfb75f106.png)
And this is where the errors happens 
![image](https://user-images.githubusercontent.com/19412591/164017071-638105c7-588e-4aa5-add9-9e8d9e878aef.png)
I tried commenting out the EnableGPS code to see if GPRS would work but that doesn't work either.

**Comment by wilba84** [comment]
Theres a few things going on here. The arduino cant supply enough power for the sim module using usb power. If you plug 12v dc into the arduino, it will supply the sim7000 via the vin pin.
Once you do that the module will start replying.
I think from memory, you will notice the lights dont turn on or they are dim on the sim7000. After adding the dc power to arduino your sim7000 lights should turn on.
Let me know how you go

**Comment by danielkp1234** [comment]
@wilba84 
![image](https://user-images.githubusercontent.com/19412591/164069733-1dcb048c-008c-4219-b0c8-c6f08c835c1f.png)
I am afraid that isn't the issue i am currently powering the module using barrel jack and a 12v adapter and i mean it looks to be communicating with the module since it says it found something

**Comment by wilba84** [comment]
Do you have the same issue with it finding the wrong module using the. “Sim7xxxx lte demo” that I sent you?

**Comment by wilba84** [comment]
Also I can see in the pastebin code that you need to init a different serial port, and use jumper wires from that port back to d7/8. This will allow the modules to communicate via serial but have their own lines for debugging

**Comment by danielkp1234** [comment]
> Do you have the same issue with it finding the wrong module using the. “Sim7xxxx lte demo” that I sent you?

No, thats the same



> Also I can see in the pastebin code that you need to init a different serial port, and use jumper wires from that port back to d7/8. This will allow the modules to communicate via serial but have their own lines for debugging

I am not really sure i understand

**Comment by wilba84** [comment]
The switch on the sim7000 allows you to select where rx and tx go on the shield, 0/1 serial pins are used by usb for the serial monitor so you can debug.
By selecting 7/8 your sending serial there on the sim7000 but you need to bridge the connection to a spare serial port on the arduino. 
ive just realised your not using a arduino mega, so you only have a single hw serial port(0,1) which is already used by usb debug. You will have to go back to software serial and set it up for 7/8

**Comment by danielkp1234** [comment]
> The switch on the sim7000 allows you to select where rx and tx go on the shield, 0/1 serial pins are used by usb for the serial monitor so you can debug. By selecting 7/8 your sending serial there on the sim7000 but you need to bridge the connection to a spare serial port on the arduino. ive just realised your not using a arduino mega, so you only have a single hw serial port(0,1) which is already used by usb debug. You will have to go back to software serial and set it up for 7/8

So how exactly would I go about doing that :)

**Comment by wilba84** [comment]
Ill be home in 5 hours, ill write the code, test it on mine with soft serial and send you everything :)

**Comment by danielkp1234** [comment]
Thank you so much

**Comment by danielkp1234** [comment]
So, I have tested using AT Command Tester and there I can get a connection and an IP so cellular works and GPS also works. 
So the issue must be somewhere in this library properly in the attacthService void

This is the library with the only modification being made was changing the APN in attacthService in from cmnet to internet that my provider uses as APN but it still doesn't work even though it works in the AT Command Tester Software.  
https://gist.github.com/danielkp1234/ab2ea90e5b47bd3070b7c0707d06bb61

@tangjie133 Sorry for pinging you but could you look into this issue with the library

**Comment by wilba84** [comment]
@danielkp1234 Can I talk with you on discord to go through some stuff?

**Comment by danielkp1234** [comment]
> @danielkp1234 Can I talk with you on discord to go through some stuff?

Well unfortunately i am going to be very busy today besides i think we might be in different time zones. But do you know how i could see the seriel print that is used in the .cpp libary file? That could maybe help find the issue

**Comment by wilba84** [comment]
Yeah you can open it in notepad and search for particular words.

**Comment by danielkp1234** [comment]
> Yeah you can open it in notepad and search for particular words.

What? 
If i add a serial print in the libaray .cpp file i cant see the output anywhere but the issue must be in the attacthService function

**Comment by gwen59800** [comment]
Hi everyone!

First of all, thanks to the community for the help.
Secondly, I have purchased a DFROBOT with SIM7000A and I am having the same problems as many here...

I've been through dozens of threads trying to figure out or solve the problem, but I can't...
I have contacted DFROBOT support but they don't answer the right questions.

1/ Impossible to validate the AT+COPS=1,2, "302220". It always returns an error despite the fact that the network in question is detected

2/ I bought the license of the software AT command tester, but I don't have the code to make it work and it is impossible to find it on the web.

3/ during my test phases, it is also impossible to attach a service...

Many problems on this module that I hope you can help.

For information, I am with TELUS with an iot card. The arduino mega 2560 that I use is powered in 12v separately.


Thanks and have a nice day.


EDIT: and now, I've an error when I try  to make AT+COPS=? ...
In an other module, I've not this error ...

![image](https://user-images.githubusercontent.com/114688124/193109847-a2f63710-d99e-416d-beba-0bcf315dc7e2.png)

**Comment by wilba84** [comment]
Hi Gwen,
The only way to get this module working is to use the botletics library for the sim7000, which means dfrobot support wont help. Within that library, there is demo code that shows you how it works and what you may need to change specifically for you.

Have a go with the fona.zip above, dont forget to swap out the library.
It looks like the module is responding in the screenshot but I did find that some arduinos dont pass 12v through the vin pin, from memory it was the genuine ones that dont pass it.

let me know how you go, Youll get there

**Comment by gwen59800** [comment]
Hi Wilba!

First of all, thanks for your help on this problem...
I did dl the included FONA and deleted all the libraries present.

I managed to start the program, but if I get nothing in response...

I also followed the tutorial here:
[Code from Luke 109362 in Core-electronics](https://forum.core-electronics.com.au/t/dfrobot-sim7000-shield-guide/8280)

and regrouped with the information from DFRobot...

```
  #define FONA_PWRKEY 12
  #define FONA_RST 7 // No RST pin for SIM7070
  #define FONA_TX 10 // Microcontroller RX
  #define FONA_RX 7 // Microcontroller TX
```

Is this a good idea?

Also attached is a picture of the installation in question.

- The power supply arrives in 12v via the vin/gnd pin
- I plugged together D8 and D10
- I use a mega2560.

Am I stupid ?

Thanks a lot again :-)

![image](https://user-images.githubusercontent.com/114688124/193329277-cd26964b-512b-4ac1-a9cd-c17fb48aac94.png)

I also tried with AT command tester for simcom module and I get this:

![image](https://user-images.githubusercontent.com/114688124/193331042-9f72f7bd-cab6-49c1-9235-2b0347e39e00.png)


![20220930_134935](https://user-images.githubusercontent.com/114688124/193329575-07bc3350-4def-4ff0-a990-ba6fe156be3a.jpg)

**Comment by wilba84** [comment]
The module isnt responding when you use the code I used. Comparing your screenshots, first one has it responding with error at 19200 and no response at 115200. If you change serial begin and fona serial to 19200, it might start responding.
I used jumper wires from 7/8 to serial1 for hardware serial.
Reason being that the software serial library doesnt work for it, and you should be keeping serial0 clear for usb/debug.

**Comment by gwen59800** [comment]
Thank you, do you have a picture of your wiring?

Also, did you change the port definitions?

```
  #define FONA_PWRKEY 12
  #define FONA_RST 7 // No RST pin for SIM7070
  #define FONA_TX 10 // Microcontroller RX
  #define FONA_RX 7 // Microcontroller TX
```

**Comment by wilba84** [comment]
You only need the pwrkey definition, which is correct at 12. The rx/tx definitions dont matter as they are for software serial and we are using hardware serial.

in regards to wiring, the sim7000 only has two options using the switch 0/1 which is already used for usb and debug or 7/8 which is for software serial.

what we are going to do is set the shield to 7/8 and instead use jumper wires to rx/tx1. D7 = RX1, D8= tx1

**Comment by dici1123** [comment]
Hi guys recently join to this community. I need help with my sim7000a shield. My error its failed to attach service
Im using arduino uno, tmobile sim card. Thanks for the help!!


![Capture](https://github.com/DFRobot/DFRobot_SIM7000/assets/172401114/cbaccd4e-b7f4-4178-857d-07802e961fef)

**Comment by wilba84** [comment]
Hi Dici!
Its hard to tell but I dont think your simshield is responding to the AT commands. Normally you would get “OK” responses. Try the AT command tester directly with the shield and verify the Baudrate

**Comment by dici1123** [comment]
I try that but never received a respond

**Comment by dici1123** [comment]
I used the guide too. And nothing

**Comment by wilba84** [comment]
Can you post a photo of how the hardware is set up and a screenshot of the at tester please

**Comment by dici1123** [comment]
I can’t upload a photo of the tester example because I’m not in my home and
I don’t have the shield right now with me. But I can send you the program
and what I write.


But when when I run the AT TEST, it upload good but when the program ask me
ENTER YOUR AT COMMAND, I enter the examples that the program give me.  Like
you see in the picture below, I use anyone of that.

And it never responds

**Comment by dici1123** [comment]
I can’t upload a photo of the tester example because I’m not in my home and
I don’t have the shield right now with me. But I can send you the program
and what I write.


But when when I run the AT TEST, it upload good but when the program ask me
ENTER YOUR AT COMMAND, I enter the examples that the program give me.  Like
you see in the picture below, I use anyone of that.

And it never responds

**Comment by wilba84** [comment]
Not the AT TESTER sketch, use the AT Command Tester program from simcom and plug directly into the sim7000 shield via usb

**Comment by dici1123** [comment]
Ok well tomorrow I will send the pictures using that program ok.

Thanks, let’s continue tomorrow

**Comment by dici1123** [comment]
i saw that my trial time expired. I buy a license but they said that i need
to wait 24 hours to receive the license.

My bad guys and thanks for the help

**Comment by dici1123** [comment]
guy i received the license yes!!!!!! what i need to do

**Comment by wilba84** [comment]
Plug the shield in directly and open command tester, try sending commands to see if you get a OK response

**Comment by dici1123** [comment]
Now I have this

**Comment by dici1123** [comment]
Guys just to let you know that i dont have any respond or communication via
at command.

I saw very carefully your video on youtube and for me it doesnt show up
easy like yours.

**Comment by wilba84** [comment]
I cant see any of your uploaded images but if you change the baudrate you should be able to find one that allows you to see the at commands clearly over serial

**Comment by dici1123** [comment]
Hi guys I’m reaching to see if we can have a conversation of
troubleshooting with the sim7000a shield.

**Comment by modellbauer13-commits** [comment]
<img width="960" height="1040" alt="Image" src="https://github.com/user-attachments/assets/89c9948d-b173-4ccf-8d39-6ca91c2d178c" />
Can anyone help me please? I didn't get it to anwer anything
